# Task 28
# Run the code below:
# if 2 + 2 != 4: 
#     print("2 + 2 is 4") 


# Expected output:
# Nothing
# But why did this happen?

if 2 + 2 != 4: 
    print("2 + 2 is 4") 


